TRUC-3: Criar diretórios e funções iniciais
Phill-Andrade/truco pull request #2
Opened 2021-06-25 20:22 UTC by Phill-Andrade

**Tarefa:**

[TRUC-3](https://eduardokatsurayama.atlassian.net/browse/TRUC-3)

**Checklist da tarefa:**

- [x] criar script '__init__' no diretório 'src'.
- [x] criar script 'main' no diretório 'src'.
- [x] criar diretório `preparation`.
- [x] criar script '__init__' no diretório 'preparation'.
- [x] criar script 'client' no diretório 'preparation'.
- [x] criar diretório `utils`.
- [x] criar script '__init__' no diretório 'utils'.
- [x] criar script 'constants' no diretório 'utils'.
- [x] criar `.gitignore`.
- [x] criar função 'generate_player' no script 'client'.
- [x] criar função 'generate_team' no script 'client'.
- [x] criar função 'starter_player' no script 'client'.
- [x] criar função 'order_player' no script 'client'.
- [x] criar função 'turn_manilha' no script 'client'.
- [x] criar função 'distribute_card' no script 'client'.

2021-06-27 18:02 UTC, eduardoKatsurayama requested changes

2021-06-27 21:32 UTC, Phill-Andrade commented on src/preparation/client.py
> +def generate_team(qty_teams=2):
Função de gerar times removido junto aos parâmetros das funções que a utilizava, a função de distribuição de times agora  sinaliza os dois times necessários e retorna os mesmos.

2021-06-27 21:34 UTC, Phill-Andrade commented on src/main.py
> +preparation.turn_manilha(deck)
função game_preparation criada contendo todas as funções do pacote preparation.

2021-06-28 13:01 UTC, eduardoKatsurayama approved these changes

2021-06-28 14:23 UTC, merged